/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AprendaRouteImport } from './routes/aprenda'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TorneiosRouteImport } from './routes/torneios'
import { Route as TreinosRouteImport } from './routes/treinos'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as TorneiosSlugRouteImport } from './routes/torneios_.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAprovacoesRouteImport } from './routes/_authenticated/admin/aprovacoes'
import { Route as AuthenticatedAdminFinanceiroRouteImport } from './routes/_authenticated/admin/financeiro'
import { Route as AuthenticatedAdminInscricoesRouteImport } from './routes/_authenticated/admin/inscricoes'
import { Route as AuthenticatedAdminTorneiosRouteImport } from './routes/_authenticated/admin/torneios'
import { Route as AuthenticatedAdminTreinosRouteImport } from './routes/_authenticated/admin/treinos'
import { Route as ApiMercadopagoWebhookRouteImport } from './routes/api/mercadopago/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AprendaRoute = AprendaRouteImport.update({
  id: '/aprenda',
  path: '/aprenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TorneiosRoute = TorneiosRouteImport.update({
  id: '/torneios',
  path: '/torneios',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinosRoute = TreinosRouteImport.update({
  id: '/treinos',
  path: '/treinos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const TorneiosSlugRoute = TorneiosSlugRouteImport.update({
  id: '/torneios_/$slug',
  path: '/torneios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAprovacoesRoute =
  AuthenticatedAdminAprovacoesRouteImport.update({
    id: '/aprovacoes',
    path: '/aprovacoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFinanceiroRoute =
  AuthenticatedAdminFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminInscricoesRoute =
  AuthenticatedAdminInscricoesRouteImport.update({
    id: '/inscricoes',
    path: '/inscricoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTorneiosRoute =
  AuthenticatedAdminTorneiosRouteImport.update({
    id: '/torneios',
    path: '/torneios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTreinosRoute =
  AuthenticatedAdminTreinosRouteImport.update({
    id: '/treinos',
    path: '/treinos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiMercadopagoWebhookRoute = ApiMercadopagoWebhookRouteImport.update({
  id: '/api/mercadopago/webhook',
  path: '/api/mercadopago/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aprenda': typeof AprendaRoute
  '/auth': typeof AuthRoute
  '/pagamento': typeof PagamentoRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sobre': typeof SobreRoute
  '/torneios': typeof TorneiosRoute
  '/treinos': typeof TreinosRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/torneios/$slug': typeof TorneiosSlugRoute
  '/admin/aprovacoes': typeof AuthenticatedAdminAprovacoesRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/inscricoes': typeof AuthenticatedAdminInscricoesRoute
  '/admin/torneios': typeof AuthenticatedAdminTorneiosRoute
  '/admin/treinos': typeof AuthenticatedAdminTreinosRoute
  '/api/mercadopago/webhook': typeof ApiMercadopagoWebhookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aprenda': typeof AprendaRoute
  '/auth': typeof AuthRoute
  '/pagamento': typeof PagamentoRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sobre': typeof SobreRoute
  '/torneios': typeof TorneiosRoute
  '/treinos': typeof TreinosRoute
  '/torneios/$slug': typeof TorneiosSlugRoute
  '/admin/aprovacoes': typeof AuthenticatedAdminAprovacoesRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/inscricoes': typeof AuthenticatedAdminInscricoesRoute
  '/admin/torneios': typeof AuthenticatedAdminTorneiosRoute
  '/admin/treinos': typeof AuthenticatedAdminTreinosRoute
  '/api/mercadopago/webhook': typeof ApiMercadopagoWebhookRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/aprenda': typeof AprendaRoute
  '/auth': typeof AuthRoute
  '/pagamento': typeof PagamentoRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sobre': typeof SobreRoute
  '/torneios': typeof TorneiosRoute
  '/treinos': typeof TreinosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/torneios_/$slug': typeof TorneiosSlugRoute
  '/_authenticated/admin/aprovacoes': typeof AuthenticatedAdminAprovacoesRoute
  '/_authenticated/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/_authenticated/admin/inscricoes': typeof AuthenticatedAdminInscricoesRoute
  '/_authenticated/admin/torneios': typeof AuthenticatedAdminTorneiosRoute
  '/_authenticated/admin/treinos': typeof AuthenticatedAdminTreinosRoute
  '/api/mercadopago/webhook': typeof ApiMercadopagoWebhookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aprenda'
    | '/auth'
    | '/pagamento'
    | '/redefinir-senha'
    | '/sobre'
    | '/torneios'
    | '/treinos'
    | '/admin'
    | '/torneios/$slug'
    | '/admin/aprovacoes'
    | '/admin/financeiro'
    | '/admin/inscricoes'
    | '/admin/torneios'
    | '/admin/treinos'
    | '/api/mercadopago/webhook'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aprenda'
    | '/auth'
    | '/pagamento'
    | '/redefinir-senha'
    | '/sobre'
    | '/torneios'
    | '/treinos'
    | '/torneios/$slug'
    | '/admin/aprovacoes'
    | '/admin/financeiro'
    | '/admin/inscricoes'
    | '/admin/torneios'
    | '/admin/treinos'
    | '/api/mercadopago/webhook'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/aprenda'
    | '/auth'
    | '/pagamento'
    | '/redefinir-senha'
    | '/sobre'
    | '/torneios'
    | '/treinos'
    | '/_authenticated/admin'
    | '/torneios_/$slug'
    | '/_authenticated/admin/aprovacoes'
    | '/_authenticated/admin/financeiro'
    | '/_authenticated/admin/inscricoes'
    | '/_authenticated/admin/torneios'
    | '/_authenticated/admin/treinos'
    | '/api/mercadopago/webhook'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AprendaRoute: typeof AprendaRoute
  AuthRoute: typeof AuthRoute
  PagamentoRoute: typeof PagamentoRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SobreRoute: typeof SobreRoute
  TorneiosRoute: typeof TorneiosRoute
  TreinosRoute: typeof TreinosRoute
  TorneiosSlugRoute: typeof TorneiosSlugRoute
  ApiMercadopagoWebhookRoute: typeof ApiMercadopagoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprenda': {
      id: '/aprenda'
      path: '/aprenda'
      fullPath: '/aprenda'
      preLoaderRoute: typeof AprendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torneios': {
      id: '/torneios'
      path: '/torneios'
      fullPath: '/torneios'
      preLoaderRoute: typeof TorneiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinos': {
      id: '/treinos'
      path: '/treinos'
      fullPath: '/treinos'
      preLoaderRoute: typeof TreinosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/torneios_/$slug': {
      id: '/torneios_/$slug'
      path: '/torneios/$slug'
      fullPath: '/torneios/$slug'
      preLoaderRoute: typeof TorneiosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/aprovacoes': {
      id: '/_authenticated/admin/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/admin/aprovacoes'
      preLoaderRoute: typeof AuthenticatedAdminAprovacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/financeiro': {
      id: '/_authenticated/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/inscricoes': {
      id: '/_authenticated/admin/inscricoes'
      path: '/inscricoes'
      fullPath: '/admin/inscricoes'
      preLoaderRoute: typeof AuthenticatedAdminInscricoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/torneios': {
      id: '/_authenticated/admin/torneios'
      path: '/torneios'
      fullPath: '/admin/torneios'
      preLoaderRoute: typeof AuthenticatedAdminTorneiosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/treinos': {
      id: '/_authenticated/admin/treinos'
      path: '/treinos'
      fullPath: '/admin/treinos'
      preLoaderRoute: typeof AuthenticatedAdminTreinosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/mercadopago/webhook': {
      id: '/api/mercadopago/webhook'
      path: '/api/mercadopago/webhook'
      fullPath: '/api/mercadopago/webhook'
      preLoaderRoute: typeof ApiMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAprovacoesRoute: typeof AuthenticatedAdminAprovacoesRoute
  AuthenticatedAdminFinanceiroRoute: typeof AuthenticatedAdminFinanceiroRoute
  AuthenticatedAdminInscricoesRoute: typeof AuthenticatedAdminInscricoesRoute
  AuthenticatedAdminTorneiosRoute: typeof AuthenticatedAdminTorneiosRoute
  AuthenticatedAdminTreinosRoute: typeof AuthenticatedAdminTreinosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAprovacoesRoute: AuthenticatedAdminAprovacoesRoute,
    AuthenticatedAdminFinanceiroRoute: AuthenticatedAdminFinanceiroRoute,
    AuthenticatedAdminInscricoesRoute: AuthenticatedAdminInscricoesRoute,
    AuthenticatedAdminTorneiosRoute: AuthenticatedAdminTorneiosRoute,
    AuthenticatedAdminTreinosRoute: AuthenticatedAdminTreinosRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AprendaRoute: AprendaRoute,
  AuthRoute: AuthRoute,
  PagamentoRoute: PagamentoRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SobreRoute: SobreRoute,
  TorneiosRoute: TorneiosRoute,
  TreinosRoute: TreinosRoute,
  TorneiosSlugRoute: TorneiosSlugRoute,
  ApiMercadopagoWebhookRoute: ApiMercadopagoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
